version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: userdb,catalogdb,ordersdb
    ports:
      - "5432:5432"
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq

  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq

  orders-service:
    build: ./orders-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
