spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ordersdb
    username: postgres
    password: password
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest